### ISSUE TITLE
[WebToolsE2E]Open eShopLite.sln and run, page show "There is a problem loading our products, Please try again later" after select "Products"

### ISSUE THREAD

**Issue by Susie-1989** [MicrosoftDocs/mslearn-dotnet-cloudnative-devops#6]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 7 [rel.d17.10-34902.84] (Includes Aspire 8.0.0-preview.7.24251.11)
3. Apply NuGet Feeds.
4. Install Git.

**REPRO STEPS**

1. Run command "git clone https://github.com/MicrosoftDocs/mslearn-dotnet-cloudnative-devops.git eShopLite" in Command Prompt.
2. Open eShopLite.sln solution >right click eShopLite solution > select Configure Startup Projects > select Multiple startup projects > in the Action column, select Start for both the Products and Store projects > press OK button.
3. Press F5 to run the project.
4. Select Products in the page.

**Note**: When do scenario [Tutorial: Add .NET Aspire to an existing .NET 8 microservices app](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/add-aspire-existing-app#explore-the-sample-app) meet this issue, can refer this for details information.

**ACTUAL:** Show "There is a problem loading our products, Please try again later"
![image](https://github.com/dotnet/aspire-samples/assets/41678874/f59d0021-af48-4204-a003-03984c1bd323)

**EXPECTED** Page show with no problem.

**Comment by Susie-1989** [comment]
@jamesmontemagno, according to vicperdana 's comments in issue [259](https://github.com/dotnet/aspire-samples/issues/259),
if ensure that the applicationUrl in Products launchSettings.json is defined exactly the same per appSetting.json ProductEndpoint in Store. this issue works well, so  could you help to update this solution? thanks in advance!
![image](https://github.com/dotnet/aspire-samples/assets/41678874/5cd174ce-b365-4cec-bfd7-c5cd8cd696b1)
![image](https://github.com/dotnet/aspire-samples/assets/41678874/6277ef55-4ef1-4205-bd63-09253d9f4239)

**Comment by jamesmontemagno** [comment]
Can you do a PR?
